---
version: 2.1

orbs:
  capture-tag: rvla/capture-tag@0.0.2
jobs:
  publish-docs:
    docker:
      - image: mydumper/mydumper-builder-noble
    steps:
    - run:
        command: |
          git config --global user.name "David Ducos"
          git config --global user.email "david.ducos@gmail.com"
          git clone https://github.com/mydumper/mydumper.git mydumper
          cd mydumper
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/mydumper/mydumper.git
          curl https://github.com/mydumper/mydumper_docs/info/refs?service=git-upload-pack --output ../latest_commit
          git update-index --cacheinfo 160000,$(head -2 ../latest_commit | tail -1 | cut -b9-48),docs
          git commit -am "[skip ci] Auto updated submodule references" && git push


workflows:
  version: 2
  mydumper_docs:
    jobs:
    - publish-docs
